name: Build and push a Docker image

on:
    push:
        branches: ["main", "dev"]
        tags: ["v*.*.*"]
    workflow_dispatch:
        inputs:
            git_ref:
                description: 'Git Ref (Branch, Tag or Release)'
                required: true
                default: 'dev'
                type: string
            image_name:
                description: 'Docker image name'
                required: true
                default: 'api'
                type: choice
                options:
                    - api

env:
    REGISTRY: ghcr.io

jobs:
    build-api:
        name: Build and push API image
        runs-on: ubuntu-latest
        if: ${{ github.event.inputs.image_name == 'api' || github.event.inputs.image_name == 'both' || github.event_name != 'workflow_dispatch' }}
        permissions:
            contents: read
            packages: write
            id-token: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.inputs.git_ref || github.ref }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
              with:
                  platforms: "arm64,amd64"

            - name: Setup Docker buildx
              uses: docker/setup-buildx-action@v2

            - name: Log into registry ${{ env.REGISTRY }}
              if: github.event_name != 'pull_request'
              uses: docker/login-action@v2
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract Docker metadata for API
              id: meta-api
              uses: docker/metadata-action@v5
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  images: ${{ env.REGISTRY }}/${{ github.repository }}/api
                  tags: |
                      type=raw,value=latest,enable=${{ github.ref_name == 'main' }}
                      type=raw,value=dev,enable=${{ github.ref_name == 'dev' }}
                      type=semver,pattern=v{{version}}
                      type=raw,value=${{ github.event.inputs.git_ref }},enable=${{ github.event_name == 'workflow_dispatch' }}

            - name: Build and push Docker image for API
              uses: docker/build-push-action@v5
              with:
                  context: api
                  build-args: VERSION=${{ github.event.inputs.git_ref || github.ref_name }}
                  push: ${{ github.event_name != 'pull_request' }}
                  tags: ${{ steps.meta-api.outputs.tags }}
                  platforms: linux/amd64,linux/arm64
                  labels: ${{ steps.meta-api.outputs.labels }}

